plugins {
    // ...

    // Add the dependency for the Google services Gradle plugin
    id 'com.google.gms.google-services' version '4.3.15' apply false
    id 'org.jetbrains.kotlin.android' version '2.1.20' apply false

}
allprojects {
    repositories {
      //  maven { url 'https://maven.aliyun.com/repository/public/' }
       // maven { url 'https://maven.aliyun.com/repository/central' }
       // maven { url 'https://repo.huaweicloud.com/repository/maven/' }
       // maven { url 'https://mirrors.tuna.tsinghua.edu.cn/git/flutter/download.flutter.io' }
        google()
        mavenCentral()
        subprojects {
            afterEvaluate { project ->
                if (project.hasProperty('android')) {
                    project.android {
                        if (namespace == null) {
                            namespace project.group
                        }
                    }
                }
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

